// This file is generated by npm run build:icons

export type IconName =
	| "chevron-down-filled"
	| "chevron-down"
	| "chevron-left"
	| "chevron-right"
	| "number_1"
	| "number_2"
	| "number_3"
	| "number_4"
	| "number_5"
	| "number_6"
	| "number_7"
	| "number_8"
	| "plus"
	| "search"
	| "x";
